/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'productId' : IDL.Nat,
  'imageUrl' : IDL.Opt(IDL.Text),
  'vendor' : IDL.Opt(IDL.Principal),
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const OrderConfirmation = IDL.Record({
  'status' : OrderStatus,
  'paymentMethod' : IDL.Text,
  'customer' : IDL.Principal,
  'createdAt' : Time,
  'orderId' : IDL.Nat,
  'message' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'paymentMethod' : IDL.Opt(IDL.Text),
  'confirmationText' : IDL.Opt(IDL.Text),
  'customer' : IDL.Principal,
  'createdAt' : Time,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Opt(IDL.Text),
  'unitLabel' : IDL.Opt(IDL.Text),
  'updatedAt' : Time,
  'imageUrl' : IDL.Opt(IDL.Text),
  'vendor' : IDL.Opt(IDL.Principal),
  'price' : IDL.Nat,
});
export const ExtendedRole = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'guest' : IDL.Null,
  'vendor' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkout' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)), IDL.Text],
      [OrderConfirmation],
      [],
    ),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllOrdersForCustomer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerRole' : IDL.Func([], [ExtendedRole], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductsForVendor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleAvailability' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'productId' : IDL.Nat,
    'imageUrl' : IDL.Opt(IDL.Text),
    'vendor' : IDL.Opt(IDL.Principal),
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const OrderConfirmation = IDL.Record({
    'status' : OrderStatus,
    'paymentMethod' : IDL.Text,
    'customer' : IDL.Principal,
    'createdAt' : Time,
    'orderId' : IDL.Nat,
    'message' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'paymentMethod' : IDL.Opt(IDL.Text),
    'confirmationText' : IDL.Opt(IDL.Text),
    'customer' : IDL.Principal,
    'createdAt' : Time,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Opt(IDL.Text),
    'unitLabel' : IDL.Opt(IDL.Text),
    'updatedAt' : Time,
    'imageUrl' : IDL.Opt(IDL.Text),
    'vendor' : IDL.Opt(IDL.Principal),
    'price' : IDL.Nat,
  });
  const ExtendedRole = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'guest' : IDL.Null,
    'vendor' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkout' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)), IDL.Text],
        [OrderConfirmation],
        [],
      ),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllOrdersForCustomer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerRole' : IDL.Func([], [ExtendedRole], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductsForVendor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleAvailability' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };