/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExtendedRole = { 'admin' : null } |
  { 'customer' : null } |
  { 'guest' : null } |
  { 'vendor' : null };
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'paymentMethod' : [] | [string],
  'confirmationText' : [] | [string],
  'customer' : Principal,
  'createdAt' : Time,
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderConfirmation {
  'status' : OrderStatus,
  'paymentMethod' : string,
  'customer' : Principal,
  'createdAt' : Time,
  'orderId' : bigint,
  'message' : string,
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'productId' : bigint,
  'imageUrl' : [] | [string],
  'vendor' : [] | [Principal],
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Product {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'isAvailable' : boolean,
  'description' : [] | [string],
  'unitLabel' : [] | [string],
  'updatedAt' : Time,
  'imageUrl' : [] | [string],
  'vendor' : [] | [Principal],
  'price' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkout' : ActorMethod<
    [Array<[bigint, bigint]>, string],
    OrderConfirmation
  >,
  'createProduct' : ActorMethod<
    [string, [] | [string], bigint, [] | [string], [] | [string]],
    bigint
  >,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllOrdersForCustomer' : ActorMethod<[Principal], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerRole' : ActorMethod<[], ExtendedRole>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsForVendor' : ActorMethod<[Principal], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleAvailability' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];